### ISSUE TITLE
getting multiple tracks from the iheart radio API

### ISSUE THREAD

**Issue by CrawFishFiesta** [oldlaptop/iheart-mplayer#4]
Hello,

I know this isn't the official iheart radio API, but I can't find any documentation or support for it.

I have a list of iHeartRadio track_id's and would like to obtain the song and artist names for the tracks.

Is there way to obtain pass multiple iHeartRadio track_id's at once through the iheartRadio API?

I'm currently making multiple calls to the API for a single track as shown below:

https://us.api.iheart.com/api/v1/catalog/getTrackByTrackId?trackId=37561435

Thanks a lot for your time.

**Comment by oldlaptop** [comment]
I might have briefly fiddled with the track API once, but as I promptly forgot whatever I found out, it can't have been very useful (I would only have been interested in playing audio). Everything I do actually know about the API is documented in my code and comments. Sorry I can't be of any help.
