### ISSUE TITLE
unknown stream type is present,KeyError instance: 'pivot_hls_stream'

### ISSUE THREAD

**Issue by nkgilley** [oldlaptop/iheart-mplayer#7]
$ ./iheart-url -v 2525
DEBUG: station name: DC101
DEBUG: call letters: WWDC-FM
DEBUG: location: Washington, DC, US
DEBUG: description: Washington DC's Alternative Rock
DEBUG: broadcast format: ROCKALTERNATIVE
INFO: an unknown stream type is present, please run with -v and submit a github issue
INFO: KeyError instance: 'pivot_hls_stream'
DEBUG: full dictionary dump:
DEBUG: {'format': 'ROCKALTERNATIVE', 'fccFacilityId': '8682', 'score': 0.0, 'band': 'FM', 'adswizzZones': {'display-zone': '38037', 'audio-exchange-zone': '38034', 'audio-fill-zone': '38033', 'audio-zone': '38035', 'optimized-audio-fill-zone': '38036'}, 'streams': {'secure_shoutcast_stream': 'https://c8icy.prod.playlists.ihrhls.com/2525_icy', 'pivot_hls_stream': 'https://us.api.iheart.com/api/v3/adswizzhls/redirect.m3u8?url=https%3A%2F%2Fc8.prod.playlists.ihrhls.com%2F2525%2Fplaylist.m3u8&marketId=42', 'shoutcast_stream': 'http://c8icyelb.prod.playlists.ihrhls.com/2525_icy', 'hls_stream': 'http://c8.prod.playlists.ihrhls.com/2525/playlist.m3u8', 'secure_hls_stream': 'https://c8.prod.playlists.ihrhls.com/2525/playlist.m3u8', 'secure_rtmp_stream': 'rtmp://cp20131.live.edgefcs.net/live/Was_DC_WWDC-FM_OR@152720'}, 'id': 2525, 'genres': [{'name': 'Alternative', 'sortIndex': 16, 'primary': True, 'id': 1}], 'rdsPiCode': '1F10', 'responseType': 'LIVE', 'feeds': {'site_id': '2079', 'feed': 'www.iheart.com/live/2525/'}, 'callLetters': 'WWDC-FM', 'isActive': True, 'callLetterAlias': 'WWDC-FM', 'description': "Washington DC's Alternative Rock", 'modified': '1520430666980', 'markets': [{'stateId': 10, 'cityId': 42, 'stateAbbreviation': 'DC', 'country': 'US', 'sortIndex': 5, 'primary': True, 'countryId': 1, 'city': 'Washington', 'marketId': '42', 'origin': True, 'name': 'WASHINGTON-DC'}], 'logo': 'http://i.iheart.com/v3/re/assets/images/2525.png', 'freq': '101.1', 'name': 'DC101', 'social': {'facebook': 'dc101', 'twitter': 'dc101'}, 'website': 'dc101.iheart.com', 'countries': 'US', 'cume': 900700, 'rds': 'WWDC-FM Washington', 'adswizz': {'publisher_id': '8171', 'adswizzHost': 'false', 'enableAdswizzTargeting': 'false'}, 'provider': 'Clear Channel', 'esid': '1804', 'callLetterRoyalty': 'WWDC-FM'}
no://station/found

**Comment by oldlaptop** [comment]
Thanks! The "new" stream type appears to be nothing more than a redirect wrapper hosted by iHeart around the existing hls_stream, possibly for advertising ("addswizzhls") reasons? For now I've told the script to always prefer the unwrapped HLS stream. (In this case it'll pick the nice, simple, reasonable shoutcast stream anyway.)
